id: P34243281
initial_creation_type: input
source_metadata:
  title: Parting from the Four Attachments
  language: pt
  description: 'A series of texts related to the famous four-line instruction that
    Sachen Kunga Nyingpo (1092–1158) received from Mañjuśrī:'
  volume:
    7642ecac5d9d40539cee62fd5ae527c2:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      parent: Lineage Prayers
    e09fb549dc664863ab9a1131ebaa6758:
      title: Prayer to the Lineage of Parting from the Four Attachments
      parent: Lineage Prayers
    8cad3ed5c7244c33b254e426b0f42d17:
      title: The Instructions on Parting from the Four Attachments
      parent: Root Text
    4d0dd47298b64e41aee747a7615774d0:
      title: Parting from the Four Attachments
      parent: Commentaries
    900d4599f38e4e6795ca180e97cd2903:
      title: Nubpa Rigdzin Drak's Parting from the Four Attachments
      parent: Commentaries
    6e8fef9040f24c65b7e29f51e877369b:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Commentaries
    0c81b736b4c44dfd95dcd73b4d57db55:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: Song
created_at: '2022-03-01T05:02:13.482569'
last_modified_at: '2022-03-01T05:02:13.482572'
